services:
  openvpn:
    container_name: openvpn
    image: kvnnap/openvpn:latest
    build:
      context: ovpn-create/deploy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./server:/root/server
    ports:
      - 1194:1194/tcp